name: Deploy Astro Site with TinaCMS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Remove node_modules
        run: rm -rf node_modules package-lock.json

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Install TinaCMS CLI
        run: npm install @tinacms/cli@1.7.0 --save-dev

      - name: Debug TinaCMS CLI Installation
        run: npm list @tinacms/cli

      - name: Debug node_modules/.bin
        run: ls -la ./node_modules/.bin

      - name: Generate tina-lock.json
        run: ./node_modules/.bin/tinacms build

      - name: Build Astro site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: dist
