name: Content Update

on:
  push:
    paths:
      - "src/pages/**" # Monitor changes to content files

jobs:
  update-content:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update content via TinaCMS"

      - name: Push changes
        run: git push origin main
